language: python
python:
  - "3.6"
cache: bundler
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: pages
  on:
    branch: gh-pages
install:
  - pip install numpy
  - pip3 install pandas
script:
  - ./run.sh
